source 'https://cdn.cocoapods.org/'

platform :ios, '11.0'

target 'ChatExample' do
  use_frameworks!
  pod 'MessageKit', :path => '../'
  pod 'SwiftLint', '~> 0.39.1'
  pod 'PINRemoteImage', '~> 3.0.0', :subspecs => ['iOS', 'PINCache']
  pod 'InputBarAccessoryView', :git => 'https://github.com/zinzin186/InputBarAccessoryView.git'

  target 'ChatExampleTests' do
    inherit! :search_paths
  end

  target 'ChatExampleUITests' do
    inherit! :search_paths
  end
end
